-- CreateTable
CREATE TABLE `Tickets` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `patientName` VARCHAR(255) NOT NULL,
    `cpf` VARCHAR(255) NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    `service` ENUM('MEDICAL_APPOINTMENT', 'EXAMS') NOT NULL,
    `urgency` ENUM('HIGH', 'MEDIUM', 'LOW') NOT NULL,
    `createdAt` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updatedAt` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
